Age = 25
Cats = [ "Cauchy", "Plato" ]
Pi = 3.14
Perfection = [ 6, 28, 496, 8128 ]
DOB = 1987-07-05T05:45:00Z


[redis]
netType = 'tcp'
addr = "127.0.0.1:6379"
password = "root"


[db]
host="127.0.0.1"
port="3306"
user="root"
password="root"
dbName="test"

[mgo]
dsn = "mongodb://127.0.0.1:27017/?maxPoolSize=2048"
user="root"
password="root"
dbName="test"


# debug, info, warning, error, fatal, panic
LogLevel = "debug"
MongoDBHosts = ["127.0.0.1:27017"]